### ISSUE TITLE
Add a threat modelling tool

### ISSUE THREAD

**Issue by AdSHSO** [hysnsec/awesome-threat-modelling#13]
Hi Team, 

we have developed OVVL:  https://github.com/OVVL-HSO/OVVL-Webapp

OVVL -> Open Weakness and Vulnerability Modeller

A STRIDE-based threat modelling tool that integrates CVEs. So you can do threat modeling based on STRIDE, but also analyse possible known vulnerabilities in case you already know off the shelf software components that may be used.

Best,

Andreas

**Comment by secfigo** [comment]
@AdSHSO thank you for your comment. Could you please raise the PR ?
