### ISSUE TITLE
Add Threat Modeling 

### ISSUE THREAD

**Issue by secfigo** [hysnsec/awesome-threat-modelling#3]
Add threat modeling list to awesome after 2nd Feb

**Comment by Robert-foreseeti** [comment]
Hi this is Robert from foreseeti, thanks for making this great guide, would it be possible to change the information under free tools and add these descriptions?

securiCAD Professional threat modeling tool is a free windows/Mac/ based tool that can be used for simulating models up to 100 objects.

Link to description: https://www.foreseeti.com/securicad-vanguard-for-aws/
Link to download: https://signup.report.securicad.com/

securiCAD Vanguard attack simulation-based security analysis for AWS, currently free to use as a time-limited introductory offer. No installation or privileged access is needed.

Link to description: https://www.foreseeti.com/securicad-vanguard-for-aws/
Link to signup: https://vanguard.securicad.com/get-started 

And we also have a securiCAD community with a lot of information about Threat modeling, methodology, videos, get started guides and descriptions of various models.

Here is the link: https://community.securicad.com

All the best,

//Rob
